### ISSUE TITLE
Encode '+' in query string

### ISSUE THREAD

**Issue by alsaybar** [kean/Get#35]
Hello @kean. Thank you for this library, I really admire the elegant API you achieved with this.

I've been using **Get** in a side project and stumbled into an issue where an explicitly written `+` character was not encoded when used in a query string (e.g. `domain.tld?query=value1+value2`). This resulted in an unexpected response from the API i was using.

According to a note in this [Apple Doc](https://developer.apple.com/documentation/foundation/nsurlcomponents/1407752-queryitems) which also refers to RFC 3986 and W3C, the `+` sign is a valid character for representing a space in a query string. Due to this fact it seems, the character is not automatically encoded when reading the `url` from a `URLComponents` instance. The same note suggests to preemptively encode the `+` character as well if needed.

I think it would be reasonable to add this behavior to **Get**, what are your thoughts?

I made a sample implementation in a fork [here](https://github.com/alsaybar/Get/commit/316ba6563e916affc11837485c8f8e94c9e4800b). Heavily inspired by Alamofire.

**Comment by kean** [comment]
Hi,

> Depending on the implementation receiving this URL, you may need to preemptively percent-encode the plus sign character. As an alternative, consider encoding complex and/or potentially problematic data in a more robust data-interchange format, such as JSON or XML.

The recommendation seems to be to preemptively encode it *if needed*, which can be done from the client code. I would prefer to avoid adding workarounds that are only needed for specific servers and/or requests. Get is consistent with the native behavior and this note applies to it as well.

**Comment by alsaybar** [comment]
I attempted to perform the encoding in my own code without luck. Am I missing something here?

Example:

```swift
// encoded version of "value1+value2".
let queryValue = "value1%2Bvalue2"

let queryItem = URLQueryItem(name: "query", value: queryValue)
var urlComponents = URLComponents()
urlComponents.queryItems = [queryItem]

// This is the query value of the final request being sent
urlComponents.percentEncodedQuery
// "query=value1%252Bvalue2"
```

As you can see, the `percentEncodedQuery` ends up being double encoded if you will. `%2B` becomes `%252B` and thus not decoded into a `+` when reaching the server.

**Comment by kean** [comment]
I added the new delegate method in [Get 1.0 (RC1)](https://github.com/kean/Get/releases/tag/1.0.0-rc.1)
