### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by mhamann** [kean/Get#52]
We're building an iOS framework that primarily supports SPM, but we know there are some adopters that still use CocoaPods. Could this library support CocoaPods as well?

**Comment by kean** [comment]
I'm afraid there is no CocoaPods in any of my frameworks and no plans to add it. I suggest trying binary distribution if SPM doesn't work for you right now. You can use [swift-create-xcframework](https://github.com/marketplace/actions/swift-create-xcframework) to create a binary from a Swift package.
