### ISSUE TITLE
Conforming to `Codable`

### ISSUE THREAD

**Issue by wmorgue** [kean/Get#74]
Hi Alex 🤝
Is it possible to conform a struct [Response<T>](https://github.com/kean/Get/blob/main/Sources/Get/Response.swift) to `Codable`?

My data model conforms to `Codable` and has a `Response<String>` property.
I implemented a `func encode(to encoder: Encoder) throws {` and `init(from decoder: Decoder) throws { ` but I'm getting an error: 
> `let response: URLResponse` does not conform to Codable.

I understand what this error means.

**Comment by kean** [comment]
Hi, `Response` is not designed to be `Codable`: it has `URLSessionTask`, raw response `Data`, and none of the `URLSession`-related types are `Codable`.

**Comment by wmorgue** [comment]
I realized what needed to be done 👍🏻
