### ISSUE TITLE
Problem with sending post requests

### ISSUE THREAD

**Issue by justTreme** [kean/Get#76]
Hey, I have a problem with the API client. I can't send requests with a post budy if one of the values is a boolean. Am I doing something wrong?
![Bildschirm­foto 2023-03-03 um 00 04 11](https://user-images.githubusercontent.com/10289945/222583553-e1254409-d34b-4dfe-aca8-3204fd6250ae.png)

**Comment by kean** [comment]
Hi, `body` has to be `Encodable`, and the heterogeneous dictionary isn't. I would suggest either passing a dictionary of type `[String: String]`, which is `Encodable`, or creating a custom `Encodable` struct to represent these parameters (recommended).
