### ISSUE TITLE
Cache policy customization doesn't appear in HTTP headers?

### ISSUE THREAD

**Issue by AndrewSB** [kean/Get#94]
Hey! I'm not sure when this changed, but I'm almost totally sure this was working a few months ago, I make a request using 

```swift
api.send(Paths.profiles.userId(userID).get, configure: { 
  $0.cachePolicy = .reloadIgnoringLocalAndRemoteCacheData
}).value
```

when I inspect that network request, I don't see any headers related to cache control in the request. I was expecting to see `Cache-Control: no-cache`.

I have implemented the delegate method `func client(_: APIClient, willSendRequest request: inout URLRequest) async throws`, and I add some other custom HTTP headers, like `R-Version`, those do appear in the HTTP headers, along with `Accept: application/json`, which is being set internally by Get.

Why does setting a custom cache policy not result in a `Cache-Control` header being sent up?

**Comment by kean** [comment]
> Why does setting a custom cache policy not result in a Cache-Control header being sent up?

I haven't changed much of anything in Get for more than a year now, so perhaps it's the OS changes that are to blame. I also have never used `reloadIgnoringLocalAndRemoteCacheData`.

> when I inspect that network request

Are you checking the `currentRequest` (as opposed to the original request)?

**Comment by AndrewSB** [comment]
will check tomorrow and dig deeper. 

> Are you checking the currentRequest (as opposed to the original request)?

yeah, i'm looking at the request and response in Pulse, so (i believe) i'm seeing what's actually sent over the network

**Comment by AndrewSB** [comment]
i'm looking at this now, it seems to be a bug inside Foundation, which makes no sense to me

`configure` is definitely getting called on the `Foundation.URLRequest`, which sets the `cachePolicy`, but then no headers appear

here's the `currentRequest`, right before the `dataTask` sends it to the `URLSession`

```
(lldb) po task.currentRequest
▿ Optional<URLRequest>
  ▿ some : https://develop-api.reclip.app/suggestions
    ▿ url : Optional<URL>
      ▿ some : https://develop-api.reclip.app/suggestions
        - _url : https://develop-api.reclip.app/suggestions
        - _parseInfo : nil
        - _baseParseInfo : nil
    - cachePolicy : 4
    - timeoutInterval : 60.0
    - mainDocumentURL : nil
    - networkServiceType : __C.NSURLRequestNetworkServiceType
    - allowsCellularAccess : true
    ▿ httpMethod : Optional<String>
      - some : "GET"
    ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
      ▿ some : 7 elements
        ▿ 0 : 2 elements
          - key : "R-Version"
          - value : "Reclip v1.4.10 (0)"
        ▿ 1 : 2 elements
          - key : "R-UserID"
          - value : "6241ebefac1a1c72c0baf991"
        ▿ 2 : 2 elements
          - key : "User-Agent"
          - value : "Reclip-iOS/1.4.10 (0) (iOS; arm64; Version 18.1 (Build 22B5069a)) CFNetwork/1568.200.51 Darwin/24.0.0 R-UserID/6241ebefac1a1c72c0baf991"
        ▿ 3 : 2 elements
          - key : "R-TimeZone"
          - value : "America/Los_Angeles"
        ▿ 4 : 2 elements
          - key : "R-DeviceID"
          - value : "B44A1D51-CC21-4E13-AE39-B175975321BD"
        ▿ 5 : 2 elements
          - key : "Authorization"
          - value : "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOWJlZmQzZWZmY2JiYzgyYzgzYWQwYzk3MmM4ZWE5NzhmNmYxMzciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVjbGlwLWNmM2Y1IiwiYXVkIjoicmVjbGlwLWNmM2Y1IiwiYXV0aF90aW1lIjoxNzI4OTQwOTMwLCJ1c2VyX2lkIjoiVnZQbFFucFpoUWh1bFZ0YnpaZDNPbDVqeXhyMSIsInN1YiI6IlZ2UGxRbnBaaFFodWxWdGJ6WmQzT2w1anl4cjEiLCJpYXQiOjE3MjkyNzk5OTgsImV4cCI6MTcyOTI4MzU5OCwicGhvbmVfbnVtYmVyIjoiKzE2NTA4MTU1NzgxIiwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJwaG9uZSI6WyIrMTY1MDgxNTU3ODEiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwaG9uZSJ9fQ.XInZrW8gFSVtL6zLBqkTlS3I8L_rD01qRAiY1gtTJLwaUodlPRaSI-zlekYxl2p3WH6L0MsS2t5W-lxa9Keej2kN4ksWRqm_KzIJJvrGjfJxSmeFaW2zQx1NK2bTXLBFsywgH5KD0Kd7F5b9bYxbVDkbvl-4d0PtXK-2j8iwOmfCE6UDcNpmFNFVqw8hLpFikGe3cdClupiUOpHR0__pbU8DpVqjPcsASBgadwdCj1-RfvjoMAu8GwCo9Vd5gHCKGM38lkHyW-lXuFt-QqDQcsg0hwc2NDvY9UxZu_BXgDs7lvouhZyv59kPB5CoE3Td2K2iKOVu7y-vbxsUXlf0Xw"
        ▿ 6 : 2 elements
          - key : "Accept"
          - value : "application/json"
    - httpBody : nil
    - httpBodyStream : nil
    - httpShouldHandleCookies : true
    - httpShouldUsePipelining : false
```

if i po the `cachePolicy`, i see 

```
(lldb) po task.currentRequest?.cachePolicy
reloadIgnoringLocalAndRemoteCacheData
```

but i don't see how my server is supposed to know that it should invalidate it's cache when it receives this request

**Comment by AndrewSB** [comment]
i'm not customizing the URLSession, it's using URLSession's default configuration, here's how I intialize Get 

```swift
APIClient(baseURL: createBaseURL(environment: ReclipEnvironment.current.apiEnvironment)) {
    $0.delegate = APIClient.Delegate()

    $0.encoder.keyEncodingStrategy = .convertToSnakeCase
    $0.encoder.dateEncodingStrategy = .iso8601WithFractions

    $0.decoder = ReclipAPIJSONDecoder()

    $0.sessionDelegate = Pulse.URLSessionProxyDelegate()
}
```

i've also tried disabling the `sessionDelegate` in case that was causing some issues, but that made no difference in the what the headers were

**Comment by kean** [comment]
I'm pretty sure I read somewhere that `reloadIgnoringLocalAndRemoteCacheData` was never implemented, but it was ~10 years ago, so I'm not positive on that.

**Comment by AndrewSB** [comment]
very strange, i'm kind of lost on this. i've also tried disabling `$0.delegate = APIClient.Delegate()` to see if that made any difference, none.

let me go read up on URLSession's caching behavior. and maybe just see if i can replicate this behavior using the vanilla URLSession without Get

definitely seems like this is inside Foundation

**Comment by AndrewSB** [comment]
ChatGPT seems to confirm your hunch, it seems really weird that Foundation doesn't do this. 

https://chatgpt.com/share/6712bd58-63f4-800f-903b-a9e1b56b5395

i don't always trust ChatGPT, but this seems to make sense, i'll add some of my own logic to customize the headers based on the cache policy

**Comment by AndrewSB** [comment]
so the answer, for posterity, is to add some combination of these 3 headers, depending on what your server requires

![image](https://github.com/user-attachments/assets/8a07cc4a-c6e0-49a7-af8b-ee2e35bdb3e5)

this is not a bug in Get, it's in URLSession: though the documentation states that reloadIgnoringLocalAndRemoteCacheData “instructs proxies and other intermediates to disregard their caches so far as the protocol allows.” Given this, it does seem like it should affect the headers of the request to instruct intermediaries (such as proxies) to bypass caching, but in practice, it does not modify the HTTP headers. Instead, the way this cache policy works is more nuanced.

you need to add a header yourself, based on the `cachePolicy` by implementing `APIClient`'s `func client(_: APIClient, willSendRequest request: inout URLRequest) async throws`

**Comment by kean** [comment]
Thanks for the details analysis and for posting this 🙇
